version: "3.8"

services:
  server:
    container_name: server_api
    build:
      context: .
    restart: always
    environment:
      NODE_ENV: production
      PG_HOST: ${DB_HOST}
      PG_PORT: ${DB_PORT}
      PG_USERNAME: ${DB_USER}
      PG_PASSWORD: ${DB_PASSWORD}
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: postgresql
    image: postgres:16.0-alpine3.18
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data: